server.port: 8080
management:
  endpoints.web.exposure.include: "*"
  security.enabled: false
spring:
  boot.admin.url: "http://localhost:8080"
  h2.console.enabled: true

  datasource:
    #pooled: true
    #dbCreate: create-drop
    name: devDb
    driverClassName: org.h2.Driver
    username: sa
    password:

hibernate:
  hbm2ddl.auto: create-drop
  show_sql: false
  format_sql: true
  #达不到效果
  #naming_strategy: neo.script.gorm.general.config.PrefixedNamingStrategy

#spring-boot-1.5.4.RELEASE.jar!/org/springframework/boot/logging/logback/base.xml
#org.springframework.boot.logging.logback.DefaultLogbackConfiguration
#https://logback.qos.ch/manual/layouts.html
#https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html
logging:
  file: "build/gorm-general-domain.log"
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-60.60logger{59}){cyan} %clr(:){faint} %m%n    %caller{1}${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} ${PID} --- [%t] %-40.40logger{39} : %m%n    %caller{1}${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  pattern.level: "%5p"
  level:
    # equivalent to hibernate.show_sql=true
    org.hibernate.SQL: DEBUG
    # Logs the JDBC parameters passed to a query
    #org.hibernate.type: TRACE
    neo.script: DEBUG
    org.hibernate.engine.transaction: DEBUG
    org.springframework.transaction: DEBUG
    grails.gorm.transactions: DEBUG
    org.grails.gorm.graphql: DEBUG
    graphql.GraphQL: DEBUG
    com.oembedler: DEBUG
    org.dataloader: DEBUG