management:
  endpoints.web.exposure.include: "*"
  security.enabled: false
spring:
  boot.admin.url: "http://localhost:8080"

  datasource:
    pooled: true
    name: devDb
    driverClassName: org.h2.Driver
    username: sa
    password:
